import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Editor from "../src/features/editor";
import { useRef,useState } from "react";

export default function Home() {

  const editorRef=useRef()

  const [name,setName]=useState('')

  console.log("edutirRef",JSON.stringify(editorRef.current))
  console.log('name',name)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Editor editorRef={editorRef} />

        <input type='text' value={name} onChange={(e)=> setName(e.target.value)}/>
      </div>
    </div>
  );
}
